import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6F5F5',
  },
  header: {
    backgroundColor: '#8EE6E6',
    paddingTop: 50,
    paddingBottom: 20,
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  greeting: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
    lineHeight: 32,
  },
  welcome: {
    fontSize: 16,
    color: '#4ECAC9',
    marginTop: 5,
    textAlign: 'center',
    fontWeight: '600',
  },
  statusTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    marginTop: 24,
    marginLeft: 24,
    marginBottom: 8,
  },
  scrollContent: {
    alignItems: 'center',
    paddingBottom: 24,
  },
  card: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    marginTop: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    justifyContent: 'space-between',
  },
  cardHeaderText: {
    fontSize: 16,
    color: '#222',
    fontWeight: '600',
  },
  plusIcon: {
    fontSize: 22,
    color: '#00C8C8',
    fontWeight: 'bold',
  },
  tablePlaceholder: {
    width: '100%',
    height: 90,
    backgroundColor: '#ddd',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  tableText: {
    color: '#333',
    textAlign: 'center',
    fontWeight: '500',
  },

  mapContainer: {
      width: '100%',
      height: 150,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: '#eee',
      marginTop: 8,
    },
    map: {
      width: '100%',
      height: '100%',
    },
    modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 200, 200, 0.15)', // subtle theme tint
  },
  modalContainer: {
    backgroundColor: '#E6F5F5',
    padding: 24,
    borderRadius: 18,
    width: '85%',
    elevation: 6,
    shadowColor: '#00C8C8',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    alignItems: 'stretch',
  },
  modalTitle: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#00C8C8',
    marginBottom: 14,
    textAlign: 'center',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#4ECAC9',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    backgroundColor: '#fff',
    color: '#222',
    fontSize: 16,
  },
  modalTextarea: {
    minHeight: 60,
    textAlignVertical: 'top',
  },
  modalLocation: {
    marginBottom: 16,
    color: '#4ECAC9',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
   modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
   reportList: {
    width: '100%',
    marginBottom: 14,
  },
  reportItem: {
    backgroundColor: '#E6F5F5',
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#4ECAC9',
    shadowColor: '#00C8C8',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  reportTitle: {
    fontWeight: 'bold',
    color: '#00C8C8',
    fontSize: 17,
    marginBottom: 2,
  },
  reportDescription: {
    color: '#222',
    fontSize: 13,
    marginBottom: 4,
  },
  reportLocation: {
    fontSize: 13,
    color: '#4ECAC9',
    fontWeight: '600',
  },
  

});