import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
  },
  header: {
  backgroundColor: '#FFFFFF',
  paddingTop: 20,
  paddingBottom: 25,
  paddingHorizontal: 20,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#00C8C8',
    textAlign: 'center',
  },

  statsBar: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  statsText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  map: {
    flex: 1,
  },
  legend: {
    position: 'absolute',
    top: 120,
    right: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  legendTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1A1A2E',
    marginBottom: 8,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  legendText: {
    fontSize: 11,
    color: '#666',
  },
  noReportsOverlay: {
    position: 'absolute',
    top: '40%',
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 20,
    borderRadius: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  noReportsText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 15,
    textAlign: 'center',
  },
  createReportButton: {
    backgroundColor: '#00C8C8',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
  },
  createReportButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  bottomNavBar: {
    position: 'absolute',
    bottom: 15,
    left: 15,
    right: 15,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingVertical: 15,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 5,
  },
  navIconImg: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
    tintColor: '#4ECAC9',
  },
  customMarker: {
    alignItems: 'center',
  },
  markerDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  markerTail: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    marginTop: -2,
  },
  mapModalContainer: {
  flex: 1,
  backgroundColor: '#FFFFFF',
  },
  mapModalHeader: {
    backgroundColor: '#00C8C8',
    paddingTop: 50,
    paddingBottom: 20,
  },
  mapModalHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  mapModalBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapModalBackIcon: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  mapModalTitleContainer: {
    flex: 1,
    marginLeft: 15,
  },
  mapModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  mapModalSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  mapModalHeaderSpacer: {
    width: 40,
  },
  mapModalScrollView: {
    flex: 1,
  },
  mapModalStatusCard: {
    backgroundColor: '#FFFFFF',
    margin: 20,
    marginBottom: 15,
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  mapModalStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  mapModalStatusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  mapModalStatusInfo: {
    flex: 1,
  },
  mapModalStatusLabel: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 2,
  },
  mapModalStatusValue: {
    fontSize: 18,
    fontWeight: '600',
  },
  mapModalStatusMessage: {
    fontSize: 14,
    color: '#636366',
    lineHeight: 20,
    fontStyle: 'italic',
  },
  mapModalImageSection: {
    marginHorizontal: 20,
    marginBottom: 15,
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  mapModalImage: {
    width: '100%',
    height: 200,
    borderRadius: 20,
  },
  mapModalImageOverlay: {
    position: 'absolute',
    top: 15,
    left: 15,
  },
  mapModalImageBadge: {
    backgroundColor: 'rgba(26, 26, 46, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  mapModalImageBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  mapModalDetailsCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 15,
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  mapModalDetailSection: {
    flexDirection: 'row',
    paddingVertical: 12,
  },
  mapModalDetailIcon: {
    fontSize: 20,
    marginRight: 15,
    width: 30,
    textAlign: 'center',
  },
  mapModalDetailContent: {
    flex: 1,
  },
  mapModalDetailLabel: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  mapModalDetailValue: {
    fontSize: 16,
    color: '#1A1A2E',
    fontWeight: '500',
  },
  mapModalDetailDescription: {
    fontSize: 15,
    color: '#3A3A3C',
    lineHeight: 22,
  },
  mapModalDetailTime: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 2,
  },
  mapModalDetailDivider: {
    height: 1,
    backgroundColor: '#F2F2F7',
    marginVertical: 8,
    marginLeft: 45,
  },
  mapModalMapSection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 15,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  mapModalMapHeader: {
    padding: 20,
    paddingBottom: 15,
  },
  mapModalMapTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#00C8C8',
  },
  mapModalMapContainer: {
    height: 300,
    position: 'relative',
  },
  mapModalMap: {
    flex: 1,
  },
  mapModalCustomMarker: {
    alignItems: 'center',
  },
  mapModalBottomSpace: {
    height: 30,
  },


overlay:{
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  alertContainer:{
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 25,
    width: '85%',
    maxWidth: 400,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  message:{
    fontSize: 20,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
  },

  button:{
    backgroundColor: '#00C8C8',
    paddingVertical: 10,
    paddingHorizontal: 40,
    borderRadius: 25,
    marginTop: 10,
  },

  buttonText:{
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },

  title:{
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  }, 

  
});